### ISSUE TITLE
How to remove this

### ISSUE THREAD

**Issue by dutchenkoOleg** [wbond/sublime_terminal#117]
After install this plugin my Sublime Text fall !!!!
and after re-install programm i get error - [http://prntscr.com/b6e3kj](http://prntscr.com/b6e3kj).
tell me how to remove this plugin from computer or where i can find this on computer

**Comment by dutchenkoOleg** [comment]
done it

**Comment by twolfson** [comment]
That error is being caused by `TerminalProjectFolder`, not this project:

https://packagecontrol.io/packages/TerminalProjectFolder

Although you resolved the issue, I want to document it for future users. To uninstall packages that were installed via Package Control, use the "Package Control: Remove Package" command from the command palette.

**Comment by dutchenkoOleg** [comment]
My solution was - manually clear package folders in
c:\Users\%UserName\AppData\Roaming\Sublime Text 2\
