### ISSUE TITLE
How to add Hyper with terminal?

### ISSUE THREAD

**Issue by LFeh** [wbond/sublime_terminal#149]
[hyper.is](https://hyper.is/)

Can you help me?

**Comment by twolfson** [comment]
It can be configured as with any other Terminal, open Terminal settings via "Preferences > Package Settings > Terminal > Settings – User" and update the entry to `hyper`:

https://github.com/wbond/sublime_terminal/tree/1.14.0#package-settings

```js
{
  "terminal": "hyper"
}
```

**Comment by LFeh** [comment]
I was testing it, but, doesn't work.

<img width="863" alt="screen shot 2016-12-20 at 23 44 41" src="https://cloud.githubusercontent.com/assets/3603793/21374497/4fe233c8-c70e-11e6-9d18-443a04b81672.png">

**Comment by twolfson** [comment]
Ah, I assumed since `hyper` was Node.js/Electron based there would be a CLI command on all platforms:

https://github.com/zeit/hyper/blob/1.0.0/package.json

It looks like you are on OS X so you'll need to write up `bash` script that calls AppleScript to invoke the "Hyper" application. Here's a basic script for Terminal:

https://github.com/wbond/sublime_terminal/blob/1.14.0/Terminal.sh

I'm going to guess Hyper's would look something like:

**hyper.sh:**

```bash
#!/bin/bash

CD_CMD="cd "\\\"$(pwd)\\\"" && clear"
if echo "$SHELL" | grep -E "/fish$" &> /dev/null; then
  CD_CMD="cd "\\\"$(pwd)\\\""; and clear"
fi
osascript<<END
try
	tell application "System Events"
		if (count(processes whose name is "Hyper")) is 0 then
			tell application "Hyper"
				activate
				do script "$CD_CMD"
			end tell
		else
			tell application "Hyper"
				activate
				do script "$CD_CMD"
			end tell
		end if
	end tell
end try
END
```

Then, update the Terminal settings to call the script:

```bash
{
  "terminal": "path/to/hyper.sh"
}
```

I know Hyper is relatively new but getting a lot of traction. If there's enough requests, I think we would be happy to add a script to this repo :+1:
