### ISSUE TITLE
Replacement for ST's console?

### ISSUE THREAD

**Issue by purefan** [wbond/sublime_terminal#172]
Hi!

My ideal scenario is to have the terminal inside Sublime Text, similar to how Visual Studio Code offers the terminal, is this possible or planned for Sublime_terminal?

**Comment by wbond** [comment]
That is not planned. Terminal emulators need to support all sorts of advanced features and trying to support all of those would take away from the development of Sublime Text as a text editor. Additionally, key bindings could get complicated as Sublime Text has it's own set of key bindings and then you'd have to try and resolve those against standard terminal emulator key bindings.

Since most operating systems these days support the ability to have multiple windows set up in a tiling-like configuration, it would be possible to have Sublime Text in one pane and your terminal emulator in the other. That way you get a best of breed text editor and terminal emulator, rather than a half-featured terminal emulator stuck in the middle of your text editor.
