### ISSUE TITLE
Terminal Launch with ZSH

### ISSUE THREAD

**Issue by eleonorsomosot** [wbond/sublime_terminal#179]
I have recently configured my gnome-terminal to use zsh. However, whenever I open terminal through key binding or "Open Terminal Here.." option it does not open from the selected directory it was launched from. This happened after I installed zsh.

**Comment by twolfson** [comment]
How did you configure `gnome-terminal` to use `zsh`?

**Comment by eleonorsomosot** [comment]
I followed this article https://ubuntuusertips.wordpress.com/2012/09/12/the-command-line-bash-or-zsh/

**Comment by twolfson** [comment]
Hm, that looks like everything should work properly. We use declaring the `cwd` as a parameter to change where our terminal launches:

https://github.com/wbond/sublime_terminal/blob/1.18.0/Terminal.py#L172

What happens when you run `gnome-terminal` in a folder like `/etc` in an existing terminal instance?

**Comment by eleonorsomosot** [comment]
it launches new terminal window on default directory.

**Comment by twolfson** [comment]
It sounds like an issue in either `gnome-terminal` or `zsh`. Since you said `bash` was working previously, I'm guessing a `zsh` plugin or your `.zshrc` is set up to navigate back to the home directory. My suggestion is to binary search to see what's causing it, i.e.:

- Try disabling all plugins and all lines in `.zshrc`
- Verify that `gnome-terminal` in `/etc` opens a new window in `/etc`
   - If this doesn't work, try resetting the shell to `bash` via `chsh -s /bin/bash` + logout + login
- Enable plugins (not lines in `.zshrc`)
- If verify that `gnome-terminal` in `/etc` no longer opens a new window then we know it's a plugin so disable half of those and keep on searching
- Otherwise, it's a line in `.zshrc` so enable half of those and keep on searching

I'm going to close this issue as it's unrelated to Terminal but feel free to ask more questions

**Comment by eleonorsomosot** [comment]
Thanks a lot. Will definitely try your instructions and get back to you whenever.

**Comment by eleonorsomosot** [comment]
It seems that I have checked the "Run command as a login shell" and "Run a custom command instead of my shell" options. Unchecking those solved my issue. Thanks once again for the assistance @twolfson.

**Comment by twolfson** [comment]
Ah, I didn't see those options in my `gnome-terminal`. Glad to hear you got it working =)
