### ISSUE TITLE
Allow settings to reference environment variables

### ISSUE THREAD

**Issue by johnburnett** [wbond/sublime_terminal#185]
It would be handy if settings could use environment variables, so you could do something like this:

```
{
  "terminal": "%USERPROFILE%\\bin\\Cmder.exe",
  ...
}
```

**Comment by johnburnett** [comment]
My home Windows hosts don't use the same username as the Windows hosts at my work, so hard coding something like "C:\Users\username\bin\mybin.exe" doesn't work.  Additionally, across different hosts there's nothing saying that "C:\Program Files" exists (it may be on a different drive), while %ProgramFiles% should.

**Comment by twolfson** [comment]
I have a few hesitations to adding this functionality:

- It's not backwards compatible; if someone for some reason has `%...%` in their environment path, then we'll wind up breaking that
- This only solves a limited use case when install paths share a common environment variable
    - This isn't always the case, it could be a `C:\Documents\bin\Cmder.exe` on one machine and `C:\foo\bar\baz\bin\Cmder.exe` on another and it'd be unlikely for someone to define a global environment variable exclusively for that purpose

As a result, my suggestion is to keep the Terminal settings separate for each computer and not sync them (e.g. `.gitignore`)

I'm happy to revisit this if we keep on getting the requests but it's been 2 years since we received #108 so it's definitely an edge case

**Comment by twolfson** [comment]
I'm also realizing that these executables should probably be on `%PATH%` in all cases as well so the OS is well behaved. Is there any reason `Cmder.exe` (no directory prefixes) doesn't work?
