### ISSUE TITLE
PYTHONPATH environment variable disappears in Windows' terminals

### ISSUE THREAD

**Issue by mcho421** [wbond/sublime_terminal#26]
When I try launching a new terminal (cmd or powershell) in Windows 7, the terminal that pops up doesn't have the PYTHONPATH environment variable set, which means some of the imports in my python projects don't work. My PYTHONPATH variable was setup like described in http://stackoverflow.com/a/4855685/1030774

I can get around it by doing a batch file hack for cmd, but I'm wondering whether there is a way to bypass it somehow:

C:\path\to\folder\ccmd.bat

	@echo off
	call :cdtmp > "C:\path\to\folder\cdtmp.bat"
	start "clean shell" /i "%windir%\explorer.exe" "C:\path\to\folder\cdtmp.bat"
	exit
	goto:eof
	
	:cdtmp
	echo cmd /k "cd %CD%"
	goto:eof

{Sublime Packages}\User\Terminal.sublime-settings

	{
		"terminal": "C:\\path\\to\\folder\\ccmd.bat"
	}

**Comment by twolfson** [comment]
We are leveraging `POpen` which inherits all environment variables from its parent process (e.g. `PYTHONPATH` from how Sublime Text was opened). I believe the issue might have been some older code. If the issue is still persisting and you want help debugging, please let us know.

https://docs.python.org/2/library/subprocess.html#subprocess.Popen
